version: 2
jobs:
  checkout-repo:
    docker:
      - image: circleci/node:11.13.0

    steps:
      - checkout
      - run: npm install

  test:
    docker:
      - image: circleci/node:11.13.0

    steps:
      - checkout
      - run: npm test -- --coverage

  build:
    docker:
      - image: circleci/node:11.13.0

    steps:
      - setup_remote_docker
      - run: docker build -t starodubenko/realtime-exchange-rates .

  publish:
    docker:
      - image: circleci/node:11.13.0

    steps:
      - run: echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin
      - run: docker push starodubenko/realtime-exchange-rates


workflows:
  version: 2

  frontend:
    jobs:
      - checkout-repo
      - test:
          requires:
            - checkout-repo
      - build:
          requires:
            - test
      - publish:
          requires:
            - build
