version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.13.0

    working_directory: ~/repo

    steps:
      - checkout

      - run: npm install
      - run: npm test -- --coverage

      - setup_remote_docker
      - run: docker build -t starodubenko/realtime-exchange-rates .
      - run: echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin
      - run: docker push starodubenko/realtime-exchange-rates
